name: Test Makefile build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make
      
      - name: Build project
        run: make build
      
      - name: Test build artifacts
        run: |
          # Add your tests here to check the build artifacts